# -*- coding: utf-8 -*-
"""Fubai Solver test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XztQkUIDwhW9XA9m3yjiEU9VfB9B49P7
"""

from itertools import product, permutations
from copy import deepcopy

class WuxingSolver:
    def __init__(self):
        self.size = 5
        self.symbols = list(range(5))
        self.no_clue = 5

    def get_neighbors(self, row, col):
        """Get adjacent cells (4-connected)"""
        neighbors = []
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = row + dr, col + dc
            if 0 <= nr < self.size and 0 <= nc < self.size:
                neighbors.append((nr, nc))
        return neighbors

    def is_valid_neighbor_assignment(self, always_neighbors, never_neighbors):
        """Check if neighbor assignments satisfy involution constraints"""
        # Check always neighbors involution: always[always[i]] == i
        for i in range(5):
            if always_neighbors[always_neighbors[i]] != i:
                return False

        # Check never neighbors involution: never[never[i]] == i
        for i in range(5):
            if never_neighbors[never_neighbors[i]] != i:
                return False

        # Check that always != never for each symbol
        for i in range(5):
            if always_neighbors[i] == never_neighbors[i]:
                return False

        return True

    def get_valid_neighbor_assignments(self, always_clues, never_clues):
        """Generate all valid neighbor assignments that match clues"""
        valid_assignments = []

        # Generate all possible involutions for always neighbors
        always_possibilities = []
        for perm in permutations(range(5)):
            if all(perm[perm[i]] == i for i in range(5)):
                always_possibilities.append(list(perm))

        # Generate all possible involutions for never neighbors
        never_possibilities = []
        for perm in permutations(range(5)):
            if all(perm[perm[i]] == i for i in range(5)):
                never_possibilities.append(list(perm))

        # Check all combinations
        for always_assign in always_possibilities:
            for never_assign in never_possibilities:
                # Check if assignment matches clues
                valid = True
                for i in range(5):
                    if always_clues[i] != self.no_clue and always_assign[i] != always_clues[i]:
                        valid = False
                        break
                    if never_clues[i] != self.no_clue and never_assign[i] != never_clues[i]:
                        valid = False
                        break

                if valid and self.is_valid_neighbor_assignment(always_assign, never_assign):
                    valid_assignments.append((always_assign, never_assign))

        return valid_assignments

    def check_neighbor_constraints(self, board, always_neighbors, never_neighbors):
        """Check if current board satisfies neighbor constraints"""
        for row in range(self.size):
            for col in range(self.size):
                if board[row][col] == self.no_clue:
                    continue

                symbol = board[row][col]
                neighbors = self.get_neighbors(row, col)

                # Check always neighbor constraint
                always_symbol = always_neighbors[symbol]
                has_always_neighbor = False
                for nr, nc in neighbors:
                    if board[nr][nc] == always_symbol:
                        has_always_neighbor = True
                        break
                if not has_always_neighbor:
                    return False

                # Check never neighbor constraint
                never_symbol = never_neighbors[symbol]
                for nr, nc in neighbors:
                    if board[nr][nc] == never_symbol:
                        return False

        return True

    def check_relation_constraints(self, board, h_relations, v_relations):
        """Check if board satisfies given relation constraints"""
        # Check horizontal relations
        for row in range(self.size):
            for col in range(self.size - 1):
                if h_relations[row][col] == self.no_clue:
                    continue
                if board[row][col] == self.no_clue or board[row][col + 1] == self.no_clue:
                    continue

                left_symbol = board[row][col]
                right_symbol = board[row][col + 1]
                expected_relation = h_relations[row][col]

                if expected_relation == 0:  # equals
                    if left_symbol != right_symbol:
                        return False
                elif expected_relation == 1:  # generates
                    if (left_symbol + 1) % 5 != right_symbol:
                        return False
                elif expected_relation == -1:  # generated by
                    if left_symbol != (right_symbol + 1) % 5:
                        return False
                elif expected_relation == 2:  # destroys
                    if (left_symbol + 2) % 5 != right_symbol:
                        return False
                elif expected_relation == -2:  # destroyed by
                    if left_symbol != (right_symbol + 2) % 5:
                        return False

        # Check vertical relations
        for row in range(self.size - 1):
            for col in range(self.size):
                if v_relations[row][col] == self.no_clue:
                    continue
                if board[row][col] == self.no_clue or board[row + 1][col] == self.no_clue:
                    continue

                top_symbol = board[row][col]
                bottom_symbol = board[row + 1][col]
                expected_relation = v_relations[row][col]

                if expected_relation == 0:  # equals
                    if top_symbol != bottom_symbol:
                        return False
                elif expected_relation == 1:  # generates
                    if (top_symbol + 1) % 5 != bottom_symbol:
                        return False
                elif expected_relation == -1:  # generated by
                    if top_symbol != (bottom_symbol + 1) % 5:
                        return False
                elif expected_relation == 2:  # destroys
                    if (top_symbol + 2) % 5 != bottom_symbol:
                        return False
                elif expected_relation == -2:  # destroyed by
                    if top_symbol != (bottom_symbol + 2) % 5:
                        return False

        return True

    def count_symbols(self, board):
        """Count occurrences of each symbol"""
        counts = [0] * 5
        for row in range(self.size):
            for col in range(self.size):
                if board[row][col] != self.no_clue:
                    counts[board[row][col]] += 1
        return counts

    def find_empty_cell(self, board):
        """Find first empty cell"""
        for row in range(self.size):
            for col in range(self.size):
                if board[row][col] == self.no_clue:
                    return (row, col)
        return None

    def is_complete(self, board):
        """Check if board is completely filled"""
        return self.find_empty_cell(board) is None

    def solve_recursive(self, board, h_relations, v_relations, always_neighbors, never_neighbors):
        """Recursive backtracking solver"""
        if self.is_complete(board):
            # Check if solution is valid
            symbol_counts = self.count_symbols(board)
            if all(count == 5 for count in symbol_counts):
                if (self.check_neighbor_constraints(board, always_neighbors, never_neighbors) and
                    self.check_relation_constraints(board, h_relations, v_relations)):
                    return deepcopy(board)
            return None

        # Find empty cell
        row, col = self.find_empty_cell(board)

        # Try each symbol
        for symbol in self.symbols:
            # Check if we can still place this symbol
            current_counts = self.count_symbols(board)
            if current_counts[symbol] >= 5:
                continue

            # Try placing the symbol
            board[row][col] = symbol

            # Quick constraint check for this placement
            valid_placement = True

            # Check neighbor constraints for this cell
            neighbors = self.get_neighbors(row, col)
            always_symbol = always_neighbors[symbol]
            never_symbol = never_neighbors[symbol]

            has_always_neighbor = False
            for nr, nc in neighbors:
                if board[nr][nc] == always_symbol:
                    has_always_neighbor = True
                if board[nr][nc] == never_symbol:
                    valid_placement = False
                    break

            if valid_placement and not has_always_neighbor:
                # Check if we can still satisfy always constraint
                can_satisfy_always = False
                for nr, nc in neighbors:
                    if board[nr][nc] == self.no_clue:
                        can_satisfy_always = True
                        break
                if not can_satisfy_always:
                    valid_placement = False

            # Check relation constraints involving this cell
            if valid_placement:
                if not self.check_relation_constraints(board, h_relations, v_relations):
                    valid_placement = False

            if valid_placement:
                result = self.solve_recursive(board, h_relations, v_relations, always_neighbors, never_neighbors)
                if result is not None:
                    return result

            # Backtrack
            board[row][col] = self.no_clue

        return None

    def solve(self, board_clues, h_relations_clues, v_relations_clues, always_clues, never_clues):
        """Main solve method - returns first solution found"""
        board = deepcopy(board_clues)

        # Get all valid neighbor assignments
        valid_assignments = self.get_valid_neighbor_assignments(always_clues, never_clues)

        if not valid_assignments:
            return None, None, None

        # Try each valid neighbor assignment
        for always_neighbors, never_neighbors in valid_assignments:
            solution = self.solve_recursive(board, h_relations_clues, v_relations_clues,
                                          always_neighbors, never_neighbors)
            if solution is not None:
                return solution, always_neighbors, never_neighbors

        return None, None, None

    def find_all_solutions(self, board_clues, h_relations_clues, v_relations_clues, always_clues, never_clues, max_solutions=2):
        """Find multiple solutions (up to max_solutions)"""
        board = deepcopy(board_clues)
        solutions = []

        # Get all valid neighbor assignments
        valid_assignments = self.get_valid_neighbor_assignments(always_clues, never_clues)

        if not valid_assignments:
            return solutions

        # Try each valid neighbor assignment
        for always_neighbors, never_neighbors in valid_assignments:
            solution = self.solve_recursive(board, h_relations_clues, v_relations_clues,
                                          always_neighbors, never_neighbors)
            if solution is not None:
                solutions.append((solution, always_neighbors, never_neighbors))
                if len(solutions) >= max_solutions:
                    break

        return solutions

    def is_solution_different(self, sol1, sol2):
        """Check if two solutions are different"""
        board1, always1, never1 = sol1
        board2, always2, never2 = sol2

        # Check if boards are different
        if board1 != board2:
            return True

        # Check if neighbor assignments are different
        if always1 != always2 or never1 != never2:
            return True

        return False

# Test the solver
def test_solver():
    solver = WuxingSolver()

    # Test clues
    board_clues = [
        [1, 2, 1, 2, 5],
        [1, 4, 5, 5, 2],
        [5, 0, 0, 5, 5],
        [5, 4, 5, 3, 4],
        [1, 5, 5, 4, 5]
    ]

    horizontal_relations_clues = [
        [ 5,  5,  5,  5],
        [ 5,  5,  1,  5],
        [ 5,  5,  5,  5],
        [ 5,  5,  5,  5],
        [ 5,  0,  5,  5]
    ]

    vertical_relations_clues = [
        [ 5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5],
        [ 0,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5]
    ]

    always_neighbors_clues = [5, 5, 5, 5, 5]
    never_neighbors_clues = [5, 5, 5, 5, 5]

    # Expected solution
    board_solution = [
        [1, 2, 1, 2, 1],
        [1, 4, 3, 4, 2],
        [2, 0, 0, 0, 0],
        [2, 4, 0, 3, 4],
        [1, 3, 3, 4, 3]
    ]

    always_neighbors_solution = [0, 2, 1, 4, 3]
    never_neighbors_solution = [1, 0, 3, 2, 4]

    print("Solving puzzle...")

    # Find up to 2 solutions to check uniqueness
    solutions = solver.find_all_solutions(
        board_clues, horizontal_relations_clues, vertical_relations_clues,
        always_neighbors_clues, never_neighbors_clues, max_solutions=2
    )

    if len(solutions) == 0:
        print("No solution found!")
        return

    if len(solutions) > 1:
        print("⚠️  WARNING: Multiple solutions found! The puzzle is not unique.")
        print(f"Found {len(solutions)} different solutions.")

        # Check if solutions are actually different
        all_different = True
        for i in range(len(solutions)):
            for j in range(i + 1, len(solutions)):
                if not solver.is_solution_different(solutions[i], solutions[j]):
                    all_different = False
                    break
            if not all_different:
                break

        if all_different:
            print("All solutions are genuinely different.")
        else:
            print("Some solutions may be equivalent.")

        print("\n--- SOLUTION 1 ---")
        solution_board, solution_always, solution_never = solutions[0]
        print("Board:")
        for row in solution_board:
            print(row)
        print(f"Always neighbors: {solution_always}")
        print(f"Never neighbors: {solution_never}")

        print("\n--- SOLUTION 2 ---")
        solution_board2, solution_always2, solution_never2 = solutions[1]
        print("Board:")
        for row in solution_board2:
            print(row)
        print(f"Always neighbors: {solution_always2}")
        print(f"Never neighbors: {solution_never2}")

    else:
        print("✓ Unique solution found!")
        solution_board, solution_always, solution_never = solutions[0]
        print("\nBoard:")
        for row in solution_board:
            print(row)
        print(f"\nAlways neighbors: {solution_always}")
        print(f"Never neighbors: {solution_never}")

    # Check if first solution matches expected
    solution_board, solution_always, solution_never = solutions[0]
    if (solution_board == board_solution and
        solution_always == always_neighbors_solution and
        solution_never == never_neighbors_solution):
        print("\n✓ First solution matches expected result!")
    else:
        print("\n✗ First solution differs from expected result")
        print("Expected board:")
        for row in board_solution:
            print(row)
        print(f"Expected always: {always_neighbors_solution}")
        print(f"Expected never: {never_neighbors_solution}")

if __name__ == "__main__":
    test_solver()

