# -*- coding: utf-8 -*-
"""Fubai Square Puzzle Creator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yxwpCV-HHOribAoKVfPYvYRJJkycduX
"""

from itertools import product, permutations
from copy import deepcopy
import numpy as np

class WuxingSolver:
    def __init__(self):
        self.size = 5
        self.symbols = list(range(5))
        self.no_clue = 5

    def get_neighbors(self, row, col):
        """Get adjacent cells (4-connected)"""
        neighbors = []
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = row + dr, col + dc
            if 0 <= nr < self.size and 0 <= nc < self.size:
                neighbors.append((nr, nc))
        return neighbors

    def is_valid_neighbor_assignment(self, always_neighbors, never_neighbors):
        """Check if neighbor assignments satisfy involution constraints"""
        # Check always neighbors involution: always[always[i]] == i
        for i in range(5):
            if always_neighbors[always_neighbors[i]] != i:
                return False

        # Check never neighbors involution: never[never[i]] == i
        for i in range(5):
            if never_neighbors[never_neighbors[i]] != i:
                return False

        # Check that always != never for each symbol
        for i in range(5):
            if always_neighbors[i] == never_neighbors[i]:
                return False

        return True

    def get_valid_neighbor_assignments(self, always_clues, never_clues):
        """Generate all valid neighbor assignments that match clues"""
        valid_assignments = []

        # Generate all possible involutions for always neighbors
        always_possibilities = []
        for perm in permutations(range(5)):
            if all(perm[perm[i]] == i for i in range(5)):
                always_possibilities.append(list(perm))

        # Generate all possible involutions for never neighbors
        never_possibilities = []
        for perm in permutations(range(5)):
            if all(perm[perm[i]] == i for i in range(5)):
                never_possibilities.append(list(perm))

        # Check all combinations
        for always_assign in always_possibilities:
            for never_assign in never_possibilities:
                # Check if assignment matches clues
                valid = True
                for i in range(5):
                    if always_clues[i] != self.no_clue and always_assign[i] != always_clues[i]:
                        valid = False
                        break
                    if never_clues[i] != self.no_clue and never_assign[i] != never_clues[i]:
                        valid = False
                        break

                if valid and self.is_valid_neighbor_assignment(always_assign, never_assign):
                    valid_assignments.append((always_assign, never_assign))

        return valid_assignments

    def check_neighbor_constraints(self, board, always_neighbors, never_neighbors):
        """Check if current board satisfies neighbor constraints"""
        for row in range(self.size):
            for col in range(self.size):
                if board[row][col] == self.no_clue:
                    continue

                symbol = board[row][col]
                neighbors = self.get_neighbors(row, col)

                # Check always neighbor constraint
                always_symbol = always_neighbors[symbol]
                has_always_neighbor = False
                for nr, nc in neighbors:
                    if board[nr][nc] == always_symbol:
                        has_always_neighbor = True
                        break
                if not has_always_neighbor:
                    return False

                # Check never neighbor constraint
                never_symbol = never_neighbors[symbol]
                for nr, nc in neighbors:
                    if board[nr][nc] == never_symbol:
                        return False

        return True

    def check_relation_constraints(self, board, h_relations, v_relations):
        """Check if board satisfies given relation constraints"""
        # Check horizontal relations
        for row in range(self.size):
            for col in range(self.size - 1):
                if h_relations[row][col] == self.no_clue:
                    continue
                if board[row][col] == self.no_clue or board[row][col + 1] == self.no_clue:
                    continue

                left_symbol = board[row][col]
                right_symbol = board[row][col + 1]
                expected_relation = h_relations[row][col]

                if expected_relation == 0:  # equals
                    if left_symbol != right_symbol:
                        return False
                elif expected_relation == 1:  # generates
                    if (left_symbol + 1) % 5 != right_symbol:
                        return False
                elif expected_relation == -1:  # generated by
                    if left_symbol != (right_symbol + 1) % 5:
                        return False
                elif expected_relation == 2:  # destroys
                    if (left_symbol + 2) % 5 != right_symbol:
                        return False
                elif expected_relation == -2:  # destroyed by
                    if left_symbol != (right_symbol + 2) % 5:
                        return False

        # Check vertical relations
        for row in range(self.size - 1):
            for col in range(self.size):
                if v_relations[row][col] == self.no_clue:
                    continue
                if board[row][col] == self.no_clue or board[row + 1][col] == self.no_clue:
                    continue

                top_symbol = board[row][col]
                bottom_symbol = board[row + 1][col]
                expected_relation = v_relations[row][col]

                if expected_relation == 0:  # equals
                    if top_symbol != bottom_symbol:
                        return False
                elif expected_relation == 1:  # generates
                    if (top_symbol + 1) % 5 != bottom_symbol:
                        return False
                elif expected_relation == -1:  # generated by
                    if top_symbol != (bottom_symbol + 1) % 5:
                        return False
                elif expected_relation == 2:  # destroys
                    if (top_symbol + 2) % 5 != bottom_symbol:
                        return False
                elif expected_relation == -2:  # destroyed by
                    if top_symbol != (bottom_symbol + 2) % 5:
                        return False

        return True

    def count_symbols(self, board):
        """Count occurrences of each symbol"""
        counts = [0] * 5
        for row in range(self.size):
            for col in range(self.size):
                if board[row][col] != self.no_clue:
                    counts[board[row][col]] += 1
        return counts

    def find_empty_cell(self, board):
        """Find first empty cell"""
        for row in range(self.size):
            for col in range(self.size):
                if board[row][col] == self.no_clue:
                    return (row, col)
        return None

    def is_complete(self, board):
        """Check if board is completely filled"""
        return self.find_empty_cell(board) is None

    def solve_recursive(self, board, h_relations, v_relations, always_neighbors, never_neighbors):
        """Recursive backtracking solver"""
        if self.is_complete(board):
            # Check if solution is valid
            symbol_counts = self.count_symbols(board)
            if all(count == 5 for count in symbol_counts):
                if (self.check_neighbor_constraints(board, always_neighbors, never_neighbors) and
                    self.check_relation_constraints(board, h_relations, v_relations)):
                    return deepcopy(board)
            return None

        # Find empty cell
        row, col = self.find_empty_cell(board)

        # Try each symbol
        for symbol in self.symbols:
            # Check if we can still place this symbol
            current_counts = self.count_symbols(board)
            if current_counts[symbol] >= 5:
                continue

            # Try placing the symbol
            board[row][col] = symbol

            # Quick constraint check for this placement
            valid_placement = True

            # Check neighbor constraints for this cell
            neighbors = self.get_neighbors(row, col)
            always_symbol = always_neighbors[symbol]
            never_symbol = never_neighbors[symbol]

            has_always_neighbor = False
            for nr, nc in neighbors:
                if board[nr][nc] == always_symbol:
                    has_always_neighbor = True
                if board[nr][nc] == never_symbol:
                    valid_placement = False
                    break

            if valid_placement and not has_always_neighbor:
                # Check if we can still satisfy always constraint
                can_satisfy_always = False
                for nr, nc in neighbors:
                    if board[nr][nc] == self.no_clue:
                        can_satisfy_always = True
                        break
                if not can_satisfy_always:
                    valid_placement = False

            # Check relation constraints involving this cell
            if valid_placement:
                if not self.check_relation_constraints(board, h_relations, v_relations):
                    valid_placement = False

            if valid_placement:
                result = self.solve_recursive(board, h_relations, v_relations, always_neighbors, never_neighbors)
                if result is not None:
                    return result

            # Backtrack
            board[row][col] = self.no_clue

        return None

    def solve(self, board_clues, h_relations_clues, v_relations_clues, always_clues, never_clues):
        """Main solve method - returns first solution found"""
        board = deepcopy(board_clues)

        # Get all valid neighbor assignments
        valid_assignments = self.get_valid_neighbor_assignments(always_clues, never_clues)

        if not valid_assignments:
            return None, None, None

        # Try each valid neighbor assignment
        for always_neighbors, never_neighbors in valid_assignments:
            solution = self.solve_recursive(board, h_relations_clues, v_relations_clues,
                                          always_neighbors, never_neighbors)
            if solution is not None:
                return solution, always_neighbors, never_neighbors

        return None, None, None

    def find_all_solutions(self, board_clues, h_relations_clues, v_relations_clues, always_clues, never_clues, max_solutions=2):
        """Find multiple solutions (up to max_solutions)"""
        board = deepcopy(board_clues)
        solutions = []

        # Get all valid neighbor assignments
        valid_assignments = self.get_valid_neighbor_assignments(always_clues, never_clues)

        if not valid_assignments:
            return solutions

        # Try each valid neighbor assignment
        for always_neighbors, never_neighbors in valid_assignments:
            solution = self.solve_recursive(board, h_relations_clues, v_relations_clues,
                                          always_neighbors, never_neighbors)
            if solution is not None:
                solutions.append((solution, always_neighbors, never_neighbors))
                if len(solutions) >= max_solutions:
                    break

        return solutions

    def is_solution_different(self, sol1, sol2):
        """Check if two solutions are different"""
        board1, always1, never1 = sol1
        board2, always2, never2 = sol2

        # Check if boards are different
        if board1 != board2:
            return True

        # Check if neighbor assignments are different
        if always1 != always2 or never1 != never2:
            return True

        return False


    def generate_minimal_clues(self, solution_board, h_relations, v_relations,
                               always_neighbors, never_neighbors, max_retries=5, seed=None, start_without_rule_clues=True):
        """
        Generate minimal clues by progressively masking elements from a complete solution.

        Args:
            solution_board: Complete 5x5 solution board
            h_relations: Complete horizontal relations
            v_relations: Complete vertical relations
            always_neighbors: Complete always neighbor assignments
            never_neighbors: Complete never neighbor assignments
            max_retries: Maximum retries when solver fails
            seed: Random seed for reproducibility

        Returns:
            Tuple of (board_clues, h_relations_clues, v_relations_clues, always_clues, never_clues)
        """
        import random
        if seed is not None:
            random.seed(seed)

        # Initialize clues as complete copies
        board_clues = deepcopy(solution_board)
        h_relations_clues = deepcopy(h_relations)
        v_relations_clues = deepcopy(v_relations)
        always_clues = deepcopy(always_neighbors)
        never_clues = deepcopy(never_neighbors)

        # Calculate total positions for each clue type
        # Board: 25, H-relations: 20, V-relations: 20, Always: 5, Never: 5
        # Total: 75 positions
        total_positions = 75

        masked_positions = set()
        consecutive_failures = 0

        if start_without_rule_clues:
            for i in range(len(always_clues)):
                always_clues[i] = self.no_clue
                pos_to_mask = ('always', i)
                masked_positions.add(pos_to_mask)

            for i in range(len(never_clues)):
                never_clues[i] = self.no_clue
                pos_to_mask = ('never', i)
                masked_positions.add(pos_to_mask)

        print(f"Starting minimal clue generation...")
        print(f"Total clue positions: {total_positions}")
        print("Clue type weights: Board(25/75), H-rel(20/75), V-rel(20/75), Always(5/75), Never(5/75)")

        while consecutive_failures < max_retries:
            # Get available positions to mask for each type
            available_board = [(row, col) for row in range(5) for col in range(5)
                             if ('board', row, col) not in masked_positions and board_clues[row][col] != self.no_clue]
            available_h_rel = [(row, col) for row in range(5) for col in range(4)
                              if ('h_relation', row, col) not in masked_positions and h_relations_clues[row][col] != self.no_clue]
            available_v_rel = [(row, col) for row in range(4) for col in range(5)
                              if ('v_relation', row, col) not in masked_positions and v_relations_clues[row][col] != self.no_clue]
            available_always = [i for i in range(5)
                               if ('always', i) not in masked_positions and always_clues[i] != self.no_clue]
            available_never = [i for i in range(5)
                              if ('never', i) not in masked_positions and never_clues[i] != self.no_clue]

            # Check if any positions available
            if not (available_board or available_h_rel or available_v_rel or available_always or available_never):
                print("No more positions available to mask!")
                break

            # Create weighted choice based on number of available positions in each category
            # Weight = (available_positions / total_original_positions) * original_weight
            choices = []
            weights = []

            if available_board:
                choices.append(('board', available_board))
                weights.append(25)  # 25/75 weight

            if available_h_rel:
                choices.append(('h_relation', available_h_rel))
                weights.append(20)  # 20/75 weight

            if available_v_rel:
                choices.append(('v_relation', available_v_rel))
                weights.append(20)  # 20/75 weight

            if available_always:
                choices.append(('always', available_always))
                weights.append(5)  # 5/75 weight

            if available_never:
                choices.append(('never', available_never))
                weights.append(5)  # 5/75 weight

            # Weighted random selection of clue type
            clue_type, available_positions = random.choices(choices, weights=weights)[0]

            # Randomly select specific position within chosen type
            if clue_type in ['board', 'h_relation', 'v_relation']:
                row, col = random.choice(available_positions)
                pos_to_mask = (clue_type, row, col)
            else:  # always or never
                idx = random.choice(available_positions)
                pos_to_mask = (clue_type, idx)

            # Mask the selected position
            original_value = None
            if pos_to_mask[0] == 'board':
                _, row, col = pos_to_mask
                original_value = board_clues[row][col]
                board_clues[row][col] = self.no_clue
            elif pos_to_mask[0] == 'h_relation':
                _, row, col = pos_to_mask
                original_value = h_relations_clues[row][col]
                h_relations_clues[row][col] = self.no_clue
            elif pos_to_mask[0] == 'v_relation':
                _, row, col = pos_to_mask
                original_value = v_relations_clues[row][col]
                v_relations_clues[row][col] = self.no_clue
            elif pos_to_mask[0] == 'always':
                _, idx = pos_to_mask
                original_value = always_clues[idx]
                always_clues[idx] = self.no_clue
            elif pos_to_mask[0] == 'never':
                _, idx = pos_to_mask
                original_value = never_clues[idx]
                never_clues[idx] = self.no_clue

            # Test if puzzle is still solvable and unique
            solutions = self.find_all_solutions(board_clues, h_relations_clues, v_relations_clues,
                                              always_clues, never_clues, max_solutions=2)

            if len(solutions) == 1:
                # Check if solution matches original
                sol_board, sol_always, sol_never = solutions[0]
                if (sol_board == solution_board and
                    sol_always == always_neighbors and
                    sol_never == never_neighbors):
                    # Success! Keep this masking
                    masked_positions.add(pos_to_mask)
                    consecutive_failures = 0
                    print(f"✓ Masked {pos_to_mask[0]} position, {len(masked_positions)} total masked")
                    continue

            # Failed - revert the masking
            if pos_to_mask[0] == 'board':
                _, row, col = pos_to_mask
                board_clues[row][col] = original_value
            elif pos_to_mask[0] == 'h_relation':
                _, row, col = pos_to_mask
                h_relations_clues[row][col] = original_value
            elif pos_to_mask[0] == 'v_relation':
                _, row, col = pos_to_mask
                v_relations_clues[row][col] = original_value
            elif pos_to_mask[0] == 'always':
                _, idx = pos_to_mask
                always_clues[idx] = original_value
            elif pos_to_mask[0] == 'never':
                _, idx = pos_to_mask
                never_clues[idx] = original_value

            consecutive_failures += 1
            print(f"✗ Failed to mask {pos_to_mask[0]} position, {consecutive_failures}/{max_retries} consecutive failures")

        if consecutive_failures >= max_retries:
            print(f"Reached maximum retries ({max_retries}), returning current minimal clues")

        print(f"Final result: {len(masked_positions)} positions masked out of {total_positions} total")

        # Count remaining clues by type
        remaining_board = sum(1 for row in range(5) for col in range(5) if board_clues[row][col] != self.no_clue)
        remaining_h_rel = sum(1 for row in range(5) for col in range(4) if h_relations_clues[row][col] != self.no_clue)
        remaining_v_rel = sum(1 for row in range(4) for col in range(5) if v_relations_clues[row][col] != self.no_clue)
        remaining_always = sum(1 for i in range(5) if always_clues[i] != self.no_clue)
        remaining_never = sum(1 for i in range(5) if never_clues[i] != self.no_clue)

        print(f"Remaining clues: Board({remaining_board}/25), H-rel({remaining_h_rel}/20), "
              f"V-rel({remaining_v_rel}/20), Always({remaining_always}/5), Never({remaining_never}/5)")

        return board_clues, h_relations_clues, v_relations_clues, always_clues, never_clues

# Test the solver
def test_solver():
    solver = WuxingSolver()

    # Test clues
    board_clues = [
        [1, 2, 1, 2, 5],
        [1, 4, 5, 5, 2],
        [5, 0, 0, 5, 5],
        [5, 4, 5, 3, 4],
        [1, 5, 5, 4, 5]
    ]

    horizontal_relations_clues = [
        [ 5,  5,  5,  5],
        [ 5,  5,  1,  5],
        [ 5,  5,  5,  5],
        [ 5,  5,  5,  5],
        [ 5,  0,  5,  5]
    ]

    vertical_relations_clues = [
        [ 5,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5],
        [ 0,  5,  5,  5,  5],
        [ 5,  5,  5,  5,  5]
    ]

    always_neighbors_clues = [5, 5, 5, 5, 5]
    never_neighbors_clues = [5, 5, 5, 5, 5]

    # Expected solution
    board_solution = [
        [1, 2, 1, 2, 1],
        [1, 4, 3, 4, 2],
        [2, 0, 0, 0, 0],
        [2, 4, 0, 3, 4],
        [1, 3, 3, 4, 3]
    ]

    always_neighbors_solution = [0, 2, 1, 4, 3]
    never_neighbors_solution = [1, 0, 3, 2, 4]

    print("Solving puzzle...")

    # Find up to 2 solutions to check uniqueness
    solutions = solver.find_all_solutions(
        board_clues, horizontal_relations_clues, vertical_relations_clues,
        always_neighbors_clues, never_neighbors_clues, max_solutions=2
    )

    if len(solutions) == 0:
        print("No solution found!")
        return

    if len(solutions) > 1:
        print("⚠️  WARNING: Multiple solutions found! The puzzle is not unique.")
        print(f"Found {len(solutions)} different solutions.")

        # Check if solutions are actually different
        all_different = True
        for i in range(len(solutions)):
            for j in range(i + 1, len(solutions)):
                if not solver.is_solution_different(solutions[i], solutions[j]):
                    all_different = False
                    break
            if not all_different:
                break

        if all_different:
            print("All solutions are genuinely different.")
        else:
            print("Some solutions may be equivalent.")

        print("\n--- SOLUTION 1 ---")
        solution_board, solution_always, solution_never = solutions[0]
        print("Board:")
        for row in solution_board:
            print(row)
        print(f"Always neighbors: {solution_always}")
        print(f"Never neighbors: {solution_never}")

        print("\n--- SOLUTION 2 ---")
        solution_board2, solution_always2, solution_never2 = solutions[1]
        print("Board:")
        for row in solution_board2:
            print(row)
        print(f"Always neighbors: {solution_always2}")
        print(f"Never neighbors: {solution_never2}")

    else:
        print("✓ Unique solution found!")
        solution_board, solution_always, solution_never = solutions[0]
        print("\nBoard:")
        for row in solution_board:
            print(row)
        print(f"\nAlways neighbors: {solution_always}")
        print(f"Never neighbors: {solution_never}")

    # Check if first solution matches expected
    solution_board, solution_always, solution_never = solutions[0]
    if (solution_board == board_solution and
        solution_always == always_neighbors_solution and
        solution_never == never_neighbors_solution):
        print("\n✓ First solution matches expected result!")
    else:
        print("\n✗ First solution differs from expected result")
        print("Expected board:")
        for row in board_solution:
            print(row)
        print(f"Expected always: {always_neighbors_solution}")
        print(f"Expected never: {never_neighbors_solution}")

def test_minimal_clue_generation():
    """Test the minimal clue generation function"""
    solver = WuxingSolver()

    # Use the known solution as starting point
    solution_board = [
        [2, 4, 0, 0, 4],
        [1, 3, 4, 0, 3],
        [1, 2, 3, 0, 0],
        [1, 4, 1, 3, 2],
        [2, 3, 2, 4, 1]
    ]

    always_neighbors = [0, 2, 1, 4, 3]
    never_neighbors = [1, 0, 2, 3, 4]

    mapping = np.random.permutation(5).tolist()  # [4, 1, 3, 0, 2]

    idx = np.argsort(mapping)

    always_neighbors = np.array([mapping[i] for i in always_neighbors])[idx].tolist()
    never_neighbors = np.array([mapping[i] for i in never_neighbors])[idx].tolist()

    solution_board = [[mapping[col] for col in row] for row in solution_board]

    horizontal_relations = [[(a-b+2)%5-2 for a, b in zip(row[1:], row[:-1])] for row in solution_board]

    vertical_relations = [list(t) for t in zip(*[[(a-b+2)%5-2  for a, b in zip(col[1:], col[:-1])] for col in zip(*solution_board)])]

    print("\n=== PROVIDED SOLUTIOM ===")
    print("Board solution:")
    for row in solution_board:
        print(f"{row},")

    print("\nHorizontal relation solutions:")
    for row in horizontal_relations:
        print(f"{row},")

    print("\nVertical relation solutions:")
    for row in vertical_relations:
        print(f"{row},")

    print(f"\nAlways neighbor solutions: {always_neighbors}")
    print(f"Never neighbor solutions: {never_neighbors}")

    print("Generating minimal clues from complete solution...")
    print("This may take a while as it tests many combinations...\n")

    minimal_clues = solver.generate_minimal_clues(
        solution_board, horizontal_relations, vertical_relations,
        always_neighbors, never_neighbors, max_retries=1, seed=42
    )

    board_clues, h_clues, v_clues, always_clues, never_clues = minimal_clues

    print("\n=== GENERATED MINIMAL CLUES ===")
    print("Board clues:")
    for row in board_clues:
        print(f"{row},")

    print("\nHorizontal relation clues:")
    for row in h_clues:
        print(f"{row},")

    print("\nVertical relation clues:")
    for row in v_clues:
        print(f"{row},")

    print(f"\nAlways neighbor clues: {always_clues}")
    print(f"Never neighbor clues: {never_clues}")

    # Verify the minimal clues still solve to the original solution
    print("\n=== VERIFYING MINIMAL CLUES ===")
    solutions = solver.find_all_solutions(board_clues, h_clues, v_clues,
                                        always_clues, never_clues, max_solutions=2)

    if len(solutions) == 1:
        sol_board, sol_always, sol_never = solutions[0]
        if (sol_board == solution_board and
            sol_always == always_neighbors and
            sol_never == never_neighbors):
            print("✓ Minimal clues solve to the correct unique solution!")
        else:
            print("✗ Minimal clues solve to a different solution!")
    elif len(solutions) > 1:
        print("✗ Minimal clues have multiple solutions!")
    else:
        print("✗ Minimal clues have no solution!")

if __name__ == "__main__":
    test_solver()
    print("\n" + "="*50)
    test_minimal_clue_generation()

"""```
=== GENERATED MINIMAL CLUES ===
Board clues:
['.', 2, '.', '.', 1]
['.', '.', '.', '.', '.']
['.', 0, '.', '.', '.']
['.', 4, '.', 3, '.']
['.', '.', '.', '.', '.']

Horizontal relation clues:
['.', '.', 1, '.']
['.', '.', '.', -2]
['.', '.', '.', 0]
['.', 1, '.', '.']
['.', '.', '.', -1]

Vertical relation clues:
['.', '.', '.', '.', '.']
['.', '.', '.', '.', '.']
['.', '.', '.', '.', '.']
['.', '.', '.', '.', '.']

Always neighbor clues: ['.', '.', '.', '.', '.']
Never neighbor clues: [1, 0, '.', 2, 4]

```

```
=== GENERATED MINIMAL CLUES ===
Board clues:
['.', '.', '.', '.', 1]
['.', '.', '.', '.', '.']
['.', 0, '.', '.', '.']
['.', 4, '.', 3, '.']
['.', '.', '.', '.', '.']

Horizontal relation clues:
['.', '.', 1, '.']
['.', '.', '.', -2]
['.', '.', '.', 0]
['.', 1, '.', '.']
['.', '.', '.', '.']

Vertical relation clues:
['.', '.', '.', '.', '.']
['.', '.', '.', '.', '.']
['.', '.', '.', '.', '.']
['.', '.', '.', '.', '.']

Always neighbor clues: ['.', '.', '.', '.', '.']
Never neighbor clues: [1, '.', '.', 2, 4]
```

```
=== GENERATED MINIMAL CLUES ===
Board clues:
['.', '.', '.', '.', '.']
['.', 4, '.', 4, '.']
['.', 0, '.', '.', 0]
['.', '.', 0, '.', 4]
['.', 3, '.', '.', '.']

Horizontal relation clues:
['.', '.', '.', '.']
['.', '.', '.', '.']
['.', '.', '.', '.']
['.', '.', '.', '.']
['.', '.', '.', '.']

Vertical relation clues:
['.', '.', '.', '.', '.']
['.', 1, '.', 1, '.']
['.', -1, '.', '.', '.']
[-1, -1, '.', 1, '.']

Always neighbor clues: ['.', '.', '.', '.', 3]
Never neighbor clues: ['.', '.', 3, '.', '.']
```

```
=== GENERATED MINIMAL CLUES ===
Board clues:
['.', '.', '.', '.', '.']
[1, '.', '.', '.', '.']
[2, '.', '.', '.', 0]
['.', '.', '.', '.', '.']
['.', '.', '.', '.', 3]

Horizontal relation clues:
[1, -1, '.', -1]
[-2, -1, '.', -2]
['.', 0, '.', '.']
['.', '.', -2, 1]
[2, '.', 1, '.']

Vertical relation clues:
['.', '.', '.', '.', '.']
['.', '.', '.', '.', '.']
['.', '.', 0, '.', '.']
[-1, '.', -2, '.', '.']

Always neighbor clues: ['.', '.', '.', 4, 3]
Never neighbor clues: ['.', '.', '.', '.', '.']
```

```
=== GENERATED MINIMAL CLUES ===
Board clues:
[5, 5, 5, 5, 5]
[5, 5, 5, 5, 5]
[5, 5, 5, 5, 0]
[5, 5, 5, 5, 5]
[5, 5, 5, 5, 5]

Horizontal relation clues:
[1, 5, 5, -1]
[-2, -1, 5, -2]
[5, 0, 5, 5]
[5, 5, -2, 1]
[2, 5, 1, 5]

Vertical relation clues:
[5, 5, 5, 5, 5]
[5, 5, 5, 5, 5]
[5, 5, 5, 5, 5]
[-1, 5, 5, 5, 5]

Always neighbor clues: [5, 5, 5, 4, 3]
Never neighbor clues: [5, 5, 5, 5, 5]
```

```
=== GENERATED MINIMAL CLUES ===
Board clues:
[5, 2, 5, 5, 5]
[1, 5, 5, 5, 3]
[5, 5, 5, 5, 5]
[5, 5, 5, 4, 5]
[5, 5, 5, 5, 5]

Horizontal relation clues:
[5, 5, 5, -2]
[5, -2, 5, 2]
[5, 2, 5, -1]
[0, 5, -1, 5]
[5, 5, 2, 5]

Vertical relation clues:
[1, 5, 5, 5, 5]
[5, 5, 5, 5, 5]
[5, 5, 5, 5, 5]
[5, 5, 5, 5, 5]

Always neighbor clues: [5, 5, 5, 5, 5]
Never neighbor clues: [5, 5, 5, 5, 5]
```
"""

