# -*- coding: utf-8 -*-
"""Fubai Squares v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imjWoM--zj98hTRztg5QUPWwBWWSrzK0
"""

import cupy as cp

try:
    if not cp.cuda.is_available():
      import numpy as cp
except:
    import numpy as cp

import numpy as np

cp

from tqdm.auto import tqdm

def generate_all_sequences_meshgrid(row_size, vocab_size):
    """
    Alternative implementation using np.meshgrid for generating all sequences.
    More memory efficient for smaller vocab_size and row_size.
    """
    if row_size <= 0 or vocab_size <= 0:
        raise ValueError("row_size and vocab_size must be positive integers")

    # Create arrays for each position
    arrays = [np.arange(vocab_size) for _ in range(row_size)]

    # Generate meshgrid
    grids = np.meshgrid(*arrays, indexing='ij')

    # Stack and reshape to get all sequences
    sequences = np.stack(grids, axis=-1).reshape(-1, row_size)

    return sequences

from itertools import product

def generate_partitions(row_size, vocab_size):
    """
    Generate all possible unique partitions of a sequence of length `row_size`
    into a maximum of `vocab_size` partitions using partition indices.

    Each position in the sequence gets assigned a partition ID from 0 to vocab_size-1.
    Only returns partitions that use consecutive partition IDs starting from 0.

    Args:
        row_size (int): Length of the sequence to partition
        vocab_size (int): Maximum number of partitions (partition IDs 0 to vocab_size-1)

    Returns:
        numpy.ndarray: Array of shape (n_partitions, row_size) where each row
                      represents a unique partition assignment

    Example:
        >>> partitions = generate_partitions(3, 3)
        >>> print(partitions)
        [[0 0 0]
         [0 0 1]
         [0 1 1]
         [0 1 2]]
    """
    if row_size <= 0 or vocab_size <= 0:
        return np.array([]).reshape(0, row_size)

    # Generate all possible assignments of partition IDs to positions
    all_assignments = list(product(range(vocab_size), repeat=row_size))

    valid_partitions = []

    for assignment in all_assignments:
        # Check if this assignment uses consecutive partition IDs starting from 0
        if is_valid_partition(assignment):
            valid_partitions.append(assignment)

    return np.array(valid_partitions)

def is_valid_partition(assignment):
    """
    Check if a partition assignment follows the canonical/restricted growth string pattern.

    Rules:
    1. First element must be 0
    2. Each new partition ID k can only appear if all IDs 0,1,...,k-1 have already appeared

    Args:
        assignment (tuple): Tuple of partition IDs assigned to each position

    Returns:
        bool: True if the assignment is valid
    """
    if not assignment or assignment[0] != 0:
        return False

    seen_ids = {0}  # We've seen partition 0
    next_new_id = 1  # Next new partition ID that can be introduced

    for partition_id in assignment[1:]:  # Skip first element (already checked)
        if partition_id in seen_ids:
            # Using an already seen partition ID is always valid
            continue
        elif partition_id == next_new_id:
            # Introducing the next new partition ID in sequence
            seen_ids.add(partition_id)
            next_new_id += 1
        else:
            # Invalid: trying to use partition ID that's too high
            return False

    return True

generate_partitions(4, 5)

def unique_with_inverse_indices(arr):
    """
    Returns unique elements in order of first appearance and the inverse indices.

    Parameters:
    arr (np.ndarray): Input 1D array of integers.

    Returns:
    tuple: (unique_values, inverse_indices)
    """
    unique_vals, first_indices, inverse = np.unique(arr, return_index=True, return_inverse=True)
    sorted_order = np.argsort(first_indices)
    unique_in_order = unique_vals[sorted_order]

    # Create mapping from original unique -> ordered unique index
    reorder_map = np.empty_like(sorted_order)
    reorder_map[sorted_order] = np.arange(len(sorted_order))

    reordered_inverse = reorder_map[inverse]

    return unique_in_order, reordered_inverse

unique_with_inverse_indices(np.array([3, 4, 2, 0, 0, 4, 1, 4]))

def add_rows_to_grids(all_possible_rows, all_possible_grids, grid_size, ruleset, validation_offset, batch_size=100, chunk_size=100, max_amount=10_000, is_final: bool = False):
    all_possible_grids = all_possible_grids[np.random.choice(np.arange(len(all_possible_grids)), min(max_amount, len(all_possible_grids)), replace=False)]
    row_count = all_possible_rows.shape[0]
    grid_count = all_possible_grids.shape[0]
    row_index = all_possible_grids.shape[-1]
    grids_batches = []
    batch_idx = list(range(0, grid_count, batch_size))
    for batch_i in tqdm(batch_idx):
      batch_possible_grids = all_possible_grids[batch_i:batch_i+batch_size, ...]
      batch_grid_count = batch_possible_grids.shape[0]
      batch_tiles = cp.tile(batch_possible_grids[None, :, ...], (row_count, 1, 1, 1))
      row_tiles = cp.tile(all_possible_rows[:, None, ...], (1, batch_grid_count, 1, 1))
      to_concat = [batch_tiles, row_tiles]
      batch_possible_grids = cp.concatenate(to_concat, axis=-1).reshape(row_count * batch_grid_count, grid_size, row_index+1)
      valid_mask = get_valid_grids_chunked(batch_possible_grids, grid_size, ruleset, ((0, grid_size), (0, validation_offset)), chunk_size=chunk_size, is_final=is_final)
      batch_possible_grids = batch_possible_grids[valid_mask, ...]
      batch_possible_grids = batch_possible_grids[np.random.choice(np.arange(len(batch_possible_grids)), min(max_amount//len(batch_idx)+1, len(batch_possible_grids)), replace=False)]
      grids_batches.append(batch_possible_grids)
    all_possible_grids = cp.concatenate(grids_batches, axis=0)
    all_possible_grids = all_possible_grids[np.random.choice(np.arange(len(all_possible_grids)), min(max_amount, len(all_possible_grids)), replace=False)]
    rotation_invariant = all_possible_grids.shape[-1] == all_possible_grids.shape[-2]
    if is_final:
      all_possible_grids = unique_tensors_no_relabeling(all_possible_grids, rotation_invariant=rotation_invariant)
    return all_possible_grids

from typing import List, Tuple, Set

def generate_all_transformations_vectorized(tensor_batch: np.ndarray) -> List[cp.ndarray]:
    """
    Generate all 8 transformations for a batch of 2D tensors efficiently.

    Args:
        tensor_batch: Shape (batch_size, height, width)

    Returns:
        List of 8 arrays, each with shape (batch_size, height, width) or (batch_size, width, height)
    """
    transformations = []

    # Original and 3 rotations
    current = tensor_batch
    for i in range(4):
        transformations.append(current.copy())
        current = np.rot90(current, axes=(-2, -1))

    # Horizontal flip and its 3 rotations
    flipped = np.flip(tensor_batch, axis=-1)  # flip along width
    current = flipped
    for i in range(4):
        transformations.append(current.copy())
        current = np.rot90(current, axes=(-2, -1))

    return transformations

def get_canonical_forms_vectorized(tensor_batch: np.ndarray, rotation_invariant: bool = False) -> List[Tuple[int, ...]]:
    """
    Get canonical forms for a batch of tensors efficiently.

    Args:
        tensor_batch: Shape (batch_size, height, width)
        rotation_invariant: If True, apply rotation and reflection invariance

    Returns:
        List of canonical form tuples
    """
    batch_size = tensor_batch.shape[0]
    canonical_forms = []

    if rotation_invariant:
        # Generate all transformations
        all_transforms = generate_all_transformations_vectorized(tensor_batch)

        for batch_idx in range(batch_size):
            # Get canonical form for each of the 8 transformations
            batch_canonicals = []

            for transform in all_transforms:
                tensor = transform[batch_idx]
                flat = tensor.flatten()

                # Fast relabeling using unique
                unique_vals, inverse_indices = unique_with_inverse_indices(flat)
                canonical_tuple = tuple(inverse_indices)
                batch_canonicals.append(canonical_tuple)

            # Get lexicographically smallest canonical form
            min_canonical = min(batch_canonicals)
            canonical_forms.append(min_canonical)
    else:
        # Simple relabeling only - much faster
        for batch_idx in range(batch_size):
            tensor = tensor_batch[batch_idx]
            rev_tensor = np.flip(tensor, axis=-1)
            flat = tensor.flatten()
            rev_flat = rev_tensor.flatten()

            # Fast relabeling using unique
            unique_vals, inverse_indices = unique_with_inverse_indices(flat)
            canonical_tuple = tuple(inverse_indices)
            canonical_forms.append(canonical_tuple)

            unique_vals, inverse_indices = unique_with_inverse_indices(rev_flat)
            canonical_tuple = tuple(inverse_indices)
            canonical_forms.append(canonical_tuple)

    return canonical_forms

def unique_tensors_no_relabeling_fast(tensor_batch: np.ndarray, rotation_invariant: bool = False, chunk_size=1000) -> np.ndarray:
    """
    Fast vectorized version to find unique tensors considering relabeling equivalence,
    and optionally rotations/reflections.

    Args:
        tensor_batch: Batch of tensors with shape (batch_size, height, width)
        rotation_invariant: If True, also consider rotations and reflections as equivalent

    Returns:
        Array of unique tensors (subset of input batch)
    """
    if len(tensor_batch) == 0:
        return tensor_batch

    # Handle large batches in chunks to manage memory
    if len(tensor_batch) > chunk_size:
        return process_in_chunks(tensor_batch, chunk_size, rotation_invariant)

    # Get canonical forms for all tensors
    canonical_forms = get_canonical_forms_vectorized(tensor_batch, rotation_invariant)

    # Find unique canonical forms
    seen_forms = set()
    unique_indices = []

    for i, canonical in enumerate(canonical_forms):
        canonical = tuple(v.item() for v in canonical)
        if canonical not in seen_forms:
            seen_forms.add(canonical)
            unique_indices.append(i)

    return tensor_batch[unique_indices]

def process_in_chunks(tensor_batch: np.ndarray, chunk_size: int, rotation_invariant: bool = False) -> np.ndarray:
    """Process large batches in chunks to manage memory usage."""
    unique_tensors = []
    seen_forms = set()

    for i in range(0, len(tensor_batch), chunk_size):
        end_idx = min(i + chunk_size, len(tensor_batch))
        chunk = tensor_batch[i:end_idx]

        canonical_forms = get_canonical_forms_vectorized(chunk, rotation_invariant)

        for j, canonical in enumerate(canonical_forms):
            if canonical not in seen_forms:
                seen_forms.add(canonical)
                unique_tensors.append(chunk[j])

    return np.array(unique_tensors) if unique_tensors else np.empty_like(tensor_batch[:0])

# Ultra-fast version using hash-based approach
def unique_tensors_no_relabeling_ultra_fast(tensor_batch: np.ndarray, rotation_invariant: bool = False, relabel=False) -> np.ndarray:
    """
    Ultra-fast version using optimized processing and minimal Python loops.

    Args:
        tensor_batch: Batch of tensors with shape (batch_size, height, width)
        rotation_invariant: If True, also consider rotations and reflections as equivalent

    Returns:
        Array of unique tensors (subset of input batch)
    """
    if len(tensor_batch) == 0:
        return tensor_batch

    batch_size = tensor_batch.shape[0]
    unique_indices = []
    seen_hashes = set()

    if rotation_invariant:
        # Generate all transformations
        all_transforms = generate_all_transformations_vectorized(tensor_batch)

        for batch_idx in tqdm(list(range(batch_size))):
            # Get all 8 canonical forms for this tensor
            canonicals = []

            for transform in all_transforms:
                tensor = transform[batch_idx]
                flat = tensor.flatten()

                # Fast unique + inverse for relabeling
                if relabel:
                    _, inverse = unique_with_inverse_indices(flat)
                    canonical = tuple(v.item() for v in inverse)
                else:
                    canonical = tuple(v.item() for v in flat)
                canonicals.append(canonical)

            # Get minimum canonical form
            min_canonical = min(canonicals)

            # Use hash for faster lookup
            canonical_hash = hash(min_canonical)
            if canonical_hash not in seen_hashes:
                seen_hashes.add(canonical_hash)
                unique_indices.append(batch_idx)
    else:
        # Simple relabeling only - much faster
        for batch_idx in tqdm(list(range(batch_size))):
            tensor = tensor_batch[batch_idx]
            flat = tensor.flatten()

            # Fast unique + inverse for relabeling
            if relabel:
                _, inverse = unique_with_inverse_indices(flat)
                canonical = tuple(v.item() for v in inverse)
            else:
                canonical = tuple(v.item() for v in flat)

            # Use hash for faster lookup
            canonical_hash = hash(canonical)
            if canonical_hash not in seen_hashes:
                seen_hashes.add(canonical_hash)
                unique_indices.append(batch_idx)

    return tensor_batch[unique_indices]

# Legacy function for backwards compatibility
def unique_tensors_no_relabeling(tensor_batch: cp.ndarray, rotation_invariant: bool = False, relabel=False) -> np.ndarray:
    """
    Find unique tensors from a batch where tensors are considered equivalent
    if one can be transformed to another by relabeling values, and optionally
    by rotations and reflections.

    Args:
        tensor_batch: Batch of tensors with shape (batch_size, *tensor_shape)
                     Each tensor should contain all values from 0 to vocab_size-1
        rotation_invariant: If True, also consider rotations (90°, 180°, 270°)
                           and reflections (horizontal flip) as equivalent.
                           Default: False (only relabeling invariance)

    Returns:
        Array of unique tensors (subset of input batch)
    """
    try:
      tensor_batch = cp.asnumpy(tensor_batch)
    except:
      pass
    return cp.array(unique_tensors_no_relabeling_ultra_fast(tensor_batch, rotation_invariant, relabel))

def rotate_batch_2d(batch):
    """
    Generate all 4 rotation orientations (0°, 90°, 180°, 270°) for a batch of 2D tensors.

    Args:
        batch: numpy array of shape (N, H, W) where N is batch size, H is height, W is width

    Returns:
        numpy array of shape (4*N, H, W) containing all rotations
        Order: [original, 90°, 180°, 270°] for each input tensor
    """
    if batch.ndim != 3:
        raise ValueError(f"Expected 3D input (batch_size, height, width), got {batch.ndim}D")

    batch_size, height, width = batch.shape

    # Generate all 4 rotations
    rot_0 = batch                                    # 0° (original)
    rot_90 = cp.rot90(batch, k=1, axes=(1, 2))      # 90° counterclockwise
    rot_180 = cp.rot90(batch, k=2, axes=(1, 2))     # 180°
    rot_270 = cp.rot90(batch, k=3, axes=(1, 2))     # 270° counterclockwise (90° clockwise)

    # Stack all rotations: for each original tensor, include all 4 rotations
    rotated_batch = cp.stack([rot_0, rot_90, rot_180, rot_270], axis=1)

    # Reshape to (4*N, H, W) - note that H and W might swap for 90°/270° rotations
    return rotated_batch.reshape(-1, *rotated_batch.shape[2:])

def find_fubai_squares(ruleset: cp.ndarray, batch_size: int = 100, chunk_size: int = 100, max_amount=10_000) -> cp.ndarray:
  vocab_size = ruleset.shape[-1]
  grid_size = vocab_size
  all_possible_rows = generate_all_sequences_meshgrid(grid_size, vocab_size)[:, :, None]
  all_possible_grids = all_possible_rows[..., :0]
  print(all_possible_grids.shape)
  for row_index in range(0, grid_size-1):
    all_possible_grids = add_rows_to_grids(all_possible_rows, all_possible_grids, grid_size, ruleset, row_index-1, batch_size=batch_size, chunk_size=chunk_size, max_amount=max_amount)
    print(all_possible_grids.shape)
  all_possible_grids = add_rows_to_grids(all_possible_rows, all_possible_grids, grid_size, ruleset, grid_size, batch_size=batch_size, chunk_size=chunk_size, max_amount=max_amount, is_final=True)
  print(all_possible_grids.shape)
  all_possible_grids = cp.concatenate([all_possible_grids, all_possible_grids.transpose(0, 2, 1)], axis=0)
  all_possible_grids = rotate_batch_2d(all_possible_grids)
  all_possible_grids = unique_tensors_no_relabeling(all_possible_grids, rotation_invariant=True)
  print(all_possible_grids.shape)
  return all_possible_grids

def create_onehot_mask(indices, vocab_size):
    """
    Create a one-hot encoded mask from an array of indices.

    Args:
        indices (cp.ndarray): Array of integers from 0 to vocab_size-1
        vocab_size (int): Size of vocabulary (number of possible values)

    Returns:
        cp.ndarray: One-hot encoded array with shape (*indices.shape, vocab_size)
                   where the last dimension represents which number is at each position
    """
    # Validate inputs
    if vocab_size <= 0:
        raise ValueError("vocab_size must be positive")

    if indices.size > 0:  # Only check if array is not empty
        if cp.any(indices < 0) or cp.any(indices >= vocab_size):
            raise ValueError(f"All indices must be in range [0, {vocab_size})")

    # Create one-hot encoding using advanced indexing
    # Method 1: Using cp.eye (identity matrix)
    onehot = cp.eye(vocab_size, dtype=bool)[indices]

    return onehot

def create_neighbor_multihot_mask_vectorized(onehot_mask, neighborhood='4-connected'):
    """
    Vectorized version of neighbor multi-hot encoding for better performance.
    """
    # Define neighborhood offsets
    if neighborhood == '4-connected':
        offsets = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    elif neighborhood == '8-connected':
        offsets = [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)]
    else:
        raise ValueError("neighborhood must be '4-connected' or '8-connected'")

    padding = tuple((0, 0) for i in range(len(onehot_mask.shape)-3))

    # Pad the grids to handle boundary conditions
    padded_mask = cp.pad(onehot_mask, (*padding, (1, 1), (1, 1), (0, 0)), mode='constant', constant_values=False)

    neighbor_mask = cp.zeros_like(onehot_mask, dtype=bool)
    x_size, y_size = padded_mask.shape[-3], padded_mask.shape[-2]
    for offset in offsets:
        dx, dy = offset
        offset_mask = padded_mask[..., 1-dx:x_size-dx-1, 1-dy:y_size-dy-1, :]
        neighbor_mask |= offset_mask
    return neighbor_mask

def get_valid_grids(
    grids: cp.ndarray,
    grid_size: int,
    ruleset: cp.ndarray,
    offsets: tuple[tuple[int, int], tuple[int, int]]
    ) -> cp.ndarray:
  vocab_size = ruleset.shape[-1]
  onehot_mask = create_onehot_mask(grids, vocab_size)
  onehot_ruleset = create_onehot_mask(ruleset, vocab_size)
  neighbor_mask = create_neighbor_multihot_mask_vectorized(onehot_mask)
  x_offset, y_offset = offsets

  must_set = onehot_ruleset[0, ...]
  never_set = onehot_ruleset[1, ...]

  offset_onehot = onehot_mask[..., x_offset[0]:x_offset[1], y_offset[0]:y_offset[1], :, None]
  offset_neighbor = neighbor_mask[..., x_offset[0]:x_offset[1], y_offset[0]:y_offset[1], None, :]
  nothot = ~offset_onehot
  all_neighbors = (offset_onehot & offset_neighbor).any((-4, -3))
  common_neighbors = (nothot | offset_neighbor).all((-4, -3))
  each_common_some = ((common_neighbors & must_set) == must_set).all((-1, -2))
  each_missing_some = (((~all_neighbors) & never_set) == never_set).all((-1, -2))
  less_than_max = (onehot_mask.sum((-2, -3)) < grid_size).all(-1)

  return each_missing_some & each_common_some & less_than_max

def get_final_valid_grids(
    grids: cp.ndarray,
    grid_size: int,
    ruleset: cp.ndarray,
    offsets: tuple[tuple[int, int], tuple[int, int]]
    ) -> cp.ndarray:
  vocab_size = ruleset.shape[-1]
  onehot_mask = create_onehot_mask(grids, vocab_size)
  onehot_ruleset = create_onehot_mask(ruleset, vocab_size)
  neighbor_mask = create_neighbor_multihot_mask_vectorized(onehot_mask)
  x_offset, y_offset = offsets

  must_set = onehot_ruleset[0, ...]
  never_set = onehot_ruleset[1, ...]

  offset_onehot = onehot_mask[..., x_offset[0]:x_offset[1], y_offset[0]:y_offset[1], :, None]
  offset_neighbor = neighbor_mask[..., x_offset[0]:x_offset[1], y_offset[0]:y_offset[1], None, :]
  nothot = ~offset_onehot
  all_neighbors = (offset_onehot & offset_neighbor).any((-4, -3))
  common_neighbors = (nothot | offset_neighbor).all((-4, -3))
  each_common_one = (common_neighbors == must_set).all((-1, -2))
  each_missing_one = ((~all_neighbors) == never_set).all((-1, -2))
  exactly_max = (onehot_mask.sum((-2, -3)) == grid_size).all(-1)

  return each_missing_one & each_common_one & exactly_max

# get_final_valid_grids(cp.array([[
#     [0,1,0,0,1,0],
#     [0,4,4,1,0,3],
#     [1,0,1,4,4,2],
#     [2,1,3,2,2,1],
#     [3,3,2,2,3,0],
#     [0,1,4,4,0,1]
#     ]]), 6, 5, ((0, 6), (0, 6)))

def get_valid_grids_chunked(
    grids: cp.ndarray,
    grid_size: int,
    ruleset: cp.ndarray,
    offsets: tuple[tuple[int, int], tuple[int, int]],
    chunk_size: int = 1000,
    is_final: bool = False
) -> cp.ndarray:
    """
    Further optimized version that processes grids in chunks to handle very large batches.
    """
    valid_func = get_final_valid_grids if is_final else get_valid_grids
    if grids.shape[0] <= chunk_size:
        return valid_func(grids, grid_size, ruleset, offsets)

    # Process in chunks
    results = []
    for i in (list(range(0, grids.shape[0], chunk_size))):
        end_idx = min(i + chunk_size, grids.shape[0])
        chunk = grids[i:i + chunk_size]
        chunk_result = valid_func(chunk, grid_size, ruleset, offsets)
        results.append(chunk_result)

    return cp.concatenate(results, axis=0)

from itertools import permutations, combinations_with_replacement

def get_all_rulesets(vocab_size: int):
  # i = np.arange(vocab_size)
  # perms = np.array(list(permutations(range(vocab_size))))
  # reperm = np.take_along_axis(perms, perms, axis=-1)
  # mask = (reperm == i[None, :]).all(-1)
  # perms = perms[mask, :]
  # combs = combinations_with_replacement(perms, 2)
  # combs = np.array(list(combs))
  # combs = combs[(combs[:, 0, :]!=combs[:, 1, :]).all(-1), :]
  # # i = np.tile(i[None, None, :], (len(combs), 1, 1))
  # # print(i.shape, combs.shape)
  # # combs = np.concatenate([combs, i], axis=1)
  # # combs = unique_tensors_no_relabeling(combs)
  # # combs = combs[:, :, :]
  # combs = cp.array(combs)
  combs = cp.array([
      [
          [0, 1, 2, 4, 3],
          [1, 0, 3, 2, 4]
      ],
      [
          [0, 2, 1, 4, 3],
          [1, 0, 3, 2, 4]
      ],
      [
          [0, 2, 1, 4, 3],
          [1, 0, 2, 3, 4]
      ],
  ])
  return combs

rulesets = get_all_rulesets(5)
rulesets.shape

rulesets

ruleset = rulesets[np.random.choice(range(len(rulesets)))]
ruleset

squares_5 = find_fubai_squares(ruleset, batch_size=250, chunk_size=100000, max_amount=100_000)

squares_5

